/**
 * Placeholder for local development only.
 * In production this file is regenerated by `npm run build`, which
 * reads the CALENDLY_URL environment variable. See README.md.
 */
window.MJENGOAI_CONFIG = {
  calendlyUrl: "https://calendly.com/your-team/mjengoai-pro-demo"
};
